region = "us-east-1"
environment = "dev"
instance_type = "t2.micro"
role = "nginx-app"
s3_terraform_bucket = "gloo-poc"
s3_bucket_region = "us-west-2"
slack_notify_url = "https://hooks.slack.com/services/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"
key_name = "devops_infra_mgmt"
